<?php

namespace Proxies\__CG__\Acme\TwitterBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SysUsers extends \Acme\TwitterBundle\Entity\SysUsers implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'userOauthToken', 'userOauthTokenSecret', 'userTwitterId', 'userScreenName', 'userEntryTime', 'userScreenImage', 'userLocation', 'userDescription', 'userOwnUrl', 'userFollowersCount', 'userFriendsCount', 'userCreatedAt', 'userFavouritesCount', 'userStatusesCount', 'userLanguage', 'userLastModfTime', 'userApiTweeted', 'userApiFavorated', 'userCreatorName', 'userMemberedApis', 'userCredit', 'userEntryId');
        }

        return array('__isInitialized__', 'userOauthToken', 'userOauthTokenSecret', 'userTwitterId', 'userScreenName', 'userEntryTime', 'userScreenImage', 'userLocation', 'userDescription', 'userOwnUrl', 'userFollowersCount', 'userFriendsCount', 'userCreatedAt', 'userFavouritesCount', 'userStatusesCount', 'userLanguage', 'userLastModfTime', 'userApiTweeted', 'userApiFavorated', 'userCreatorName', 'userMemberedApis', 'userCredit', 'userEntryId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SysUsers $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setUserOauthToken($userOauthToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserOauthToken', array($userOauthToken));

        return parent::setUserOauthToken($userOauthToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserOauthToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserOauthToken', array());

        return parent::getUserOauthToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserOauthTokenSecret($userOauthTokenSecret)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserOauthTokenSecret', array($userOauthTokenSecret));

        return parent::setUserOauthTokenSecret($userOauthTokenSecret);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserOauthTokenSecret()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserOauthTokenSecret', array());

        return parent::getUserOauthTokenSecret();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserTwitterId($userTwitterId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserTwitterId', array($userTwitterId));

        return parent::setUserTwitterId($userTwitterId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserTwitterId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserTwitterId', array());

        return parent::getUserTwitterId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserScreenName($userScreenName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserScreenName', array($userScreenName));

        return parent::setUserScreenName($userScreenName);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserScreenName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserScreenName', array());

        return parent::getUserScreenName();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserEntryTime($userEntryTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserEntryTime', array($userEntryTime));

        return parent::setUserEntryTime($userEntryTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserEntryTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserEntryTime', array());

        return parent::getUserEntryTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserScreenImage($userScreenImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserScreenImage', array($userScreenImage));

        return parent::setUserScreenImage($userScreenImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserScreenImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserScreenImage', array());

        return parent::getUserScreenImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserLocation($userLocation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserLocation', array($userLocation));

        return parent::setUserLocation($userLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserLocation', array());

        return parent::getUserLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserDescription($userDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserDescription', array($userDescription));

        return parent::setUserDescription($userDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserDescription', array());

        return parent::getUserDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserOwnUrl($userOwnUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserOwnUrl', array($userOwnUrl));

        return parent::setUserOwnUrl($userOwnUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserOwnUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserOwnUrl', array());

        return parent::getUserOwnUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserFollowersCount($userFollowersCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserFollowersCount', array($userFollowersCount));

        return parent::setUserFollowersCount($userFollowersCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserFollowersCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserFollowersCount', array());

        return parent::getUserFollowersCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserFriendsCount($userFriendsCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserFriendsCount', array($userFriendsCount));

        return parent::setUserFriendsCount($userFriendsCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserFriendsCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserFriendsCount', array());

        return parent::getUserFriendsCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCreatedAt($userCreatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCreatedAt', array($userCreatedAt));

        return parent::setUserCreatedAt($userCreatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCreatedAt', array());

        return parent::getUserCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserFavouritesCount($userFavouritesCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserFavouritesCount', array($userFavouritesCount));

        return parent::setUserFavouritesCount($userFavouritesCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserFavouritesCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserFavouritesCount', array());

        return parent::getUserFavouritesCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserStatusesCount($userStatusesCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserStatusesCount', array($userStatusesCount));

        return parent::setUserStatusesCount($userStatusesCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserStatusesCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserStatusesCount', array());

        return parent::getUserStatusesCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserLanguage($userLanguage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserLanguage', array($userLanguage));

        return parent::setUserLanguage($userLanguage);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserLanguage', array());

        return parent::getUserLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserLastModfTime($userLastModfTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserLastModfTime', array($userLastModfTime));

        return parent::setUserLastModfTime($userLastModfTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserLastModfTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserLastModfTime', array());

        return parent::getUserLastModfTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserApiTweeted($userApiTweeted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserApiTweeted', array($userApiTweeted));

        return parent::setUserApiTweeted($userApiTweeted);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserApiTweeted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserApiTweeted', array());

        return parent::getUserApiTweeted();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserApiFavorated($userApiFavorated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserApiFavorated', array($userApiFavorated));

        return parent::setUserApiFavorated($userApiFavorated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserApiFavorated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserApiFavorated', array());

        return parent::getUserApiFavorated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCreatorName($userCreatorName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCreatorName', array($userCreatorName));

        return parent::setUserCreatorName($userCreatorName);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCreatorName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCreatorName', array());

        return parent::getUserCreatorName();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserMemberedApis($userMemberedApis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserMemberedApis', array($userMemberedApis));

        return parent::setUserMemberedApis($userMemberedApis);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserMemberedApis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserMemberedApis', array());

        return parent::getUserMemberedApis();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCredit($userCredit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCredit', array($userCredit));

        return parent::setUserCredit($userCredit);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCredit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCredit', array());

        return parent::getUserCredit();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserEntryId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getUserEntryId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserEntryId', array());

        return parent::getUserEntryId();
    }

}
