<?php

namespace Proxies\__CG__\Acme\TwitterBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SysPackets extends \Acme\TwitterBundle\Entity\SysPackets implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'miktar', 'paketTipi', 'tlKarsiligi', 'isOnline', 'packetTypeInt', 'time', 'creator', 'totalComing', 'extraInfo', 'eid');
        }

        return array('__isInitialized__', 'miktar', 'paketTipi', 'tlKarsiligi', 'isOnline', 'packetTypeInt', 'time', 'creator', 'totalComing', 'extraInfo', 'eid');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SysPackets $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setMiktar($miktar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMiktar', array($miktar));

        return parent::setMiktar($miktar);
    }

    /**
     * {@inheritDoc}
     */
    public function getMiktar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMiktar', array());

        return parent::getMiktar();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaketTipi($paketTipi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaketTipi', array($paketTipi));

        return parent::setPaketTipi($paketTipi);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaketTipi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaketTipi', array());

        return parent::getPaketTipi();
    }

    /**
     * {@inheritDoc}
     */
    public function setTlKarsiligi($tlKarsiligi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTlKarsiligi', array($tlKarsiligi));

        return parent::setTlKarsiligi($tlKarsiligi);
    }

    /**
     * {@inheritDoc}
     */
    public function getTlKarsiligi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTlKarsiligi', array());

        return parent::getTlKarsiligi();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsOnline($isOnline)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsOnline', array($isOnline));

        return parent::setIsOnline($isOnline);
    }

    /**
     * {@inheritDoc}
     */
    public function setPacketTypeInt($packetTypeInt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPacketTypeInt', array($packetTypeInt));

        return parent::setPacketTypeInt($packetTypeInt);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsOnline()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsOnline', array());

        return parent::getIsOnline();
    }

    /**
     * {@inheritDoc}
     */
    public function getPacketTypeInt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPacketTypeInt', array());

        return parent::getPacketTypeInt();
    }

    /**
     * {@inheritDoc}
     */
    public function setTime($time)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTime', array($time));

        return parent::setTime($time);
    }

    /**
     * {@inheritDoc}
     */
    public function getTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTime', array());

        return parent::getTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreator($creator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreator', array($creator));

        return parent::setCreator($creator);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreator', array());

        return parent::getCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalComing($totalComing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalComing', array($totalComing));

        return parent::setTotalComing($totalComing);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalComing()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalComing', array());

        return parent::getTotalComing();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtraInfo($extraInfo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtraInfo', array($extraInfo));

        return parent::setExtraInfo($extraInfo);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtraInfo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtraInfo', array());

        return parent::getExtraInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function getEid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getEid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEid', array());

        return parent::getEid();
    }

}
